services:
  - type: web
    name: gefen-kesafim-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 8 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 45 --graceful-timeout 20
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
